[server]
port = 8501
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = true

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
serverAddress = "localhost"
gatherUsageStats = false